secrets:
  postgres_user_file:
    file: ./db_user.txt
  postgres_password_file:
    file: ./db_password.txt
  postgres_db_file:
    file: ./db_name.txt

services:
  contracts:
    image: ghcr.io/unibo-prismlab/contracts:main
    build:
      context: ./contracts
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8545"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - uip-net
    ports:
      - "8545:8545"

  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    networks:
      - uip-net
    secrets:
      - postgres_user_file
      - postgres_password_file
      - postgres_db_file
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user_file
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password_file
      POSTGRES_DB_FILE: /run/secrets/postgres_db_file
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./nip-backend/init-scripts:/docker-entrypoint-initdb.d

  nip-backend:
    image: ghcr.io/unibo-prismlab/nip-backend:main
    build:
      context: ./nip-backend
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 16
    depends_on:
      - db
      - contracts
    networks:
      - uip-net
    ports:
      - "8888:8888"
    environment:
      - TASK_SLOT={{.Task.Slot}}
    volumes:
      - ./nip-backend/configs:/app/configs

volumes:
  db_data:

networks:
  uip-net:
    driver: overlay
