services:
  # nip:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   develop:
  #     watch:
  #       - path: ./docs
  #         action: rebuild
  #       - path: ./api
  #         action: rebuild
  #       - path: ./db
  #         action: rebuild
  #   image: nip:latest
  #   networks:
  #     - nip-net
  #   ports:
  #     - "8888:8888"
  #   environment:
  #     - DATABASE_URL=postgres://nipadmin:password@db:5432/nip
  #     - ETH_NODE_URL="http://host.docker.internal:8545"
  #     - CONTRACT_ADDRESS="0x5FbDB2315678afecb367f032d93F642f64180aa3"
  #   depends_on:
  #     - db

  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    networks:
      - nip-net
    environment:
      POSTGRES_USER: nipadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nip
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    networks:
      - nip-net
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  db_data:

networks:
  nip-net:
    driver: bridge
